title: Bullwinkle and friends
# theme: jekyll-theme-minimal
# remote_theme: ItsMeaga1n/minimal-categorized
subtitle: "Public space"
description: "Bullwinkle-org's public space for blog, portfolio, static content and experiments."
share: "Bullwinkle and friends public space"
url: https://bullwinkle.space

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
    values:
      layout: "default"

paginate: 4
paginate_path: "/paginating/page:num/"
permalink: pretty
page_excerpts: true
collections_dir: collections

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

exclude: ['node_modules']   