title: Bullwinkle-org
theme: jekyll-theme-minimal
subtitle: "Public monitoring page"
description: "Description"
share: "Shared"
url: https://www.bullwinkle.ml
permalink: pretty
exclude: ['node_modules']
