title: Bullwinkle and friends
# theme: jekyll-theme-minimal
# remote_theme: ItsMeaga1n/minimal-categorized
subtitle: "Public space"
description: "Bullwinkle and friends blog"
share: "Bullwinkle and friends public space"
url: https://bullwinkle.space

permalink: pretty
sass:
  style: compressed
exclude: ['node_modules']

collections_dir: collections
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
    values:
      layout: "default"

paginate: 10      

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag      