title: Bullwinkle and friends
# theme: jekyll-theme-minimal
# remote_theme: ItsMeaga1n/minimal-categorized
subtitle: "Public space"
description: "Bullwinkle and friends blog"
share: "Bullwinkle and friends public space"
url: https://bullwinkle.space
permalink: pretty
sass:
  style: compressed
exclude: ['node_modules']
