title: Bullwinkle and friends
# theme: jekyll-theme-minimal
# remote_theme: ItsMeaga1n/minimal-categorized
subtitle: "Public space"
description: "Bullwinkle-org's public space for blog, portfolio, static content and experiments."
share: "Bullwinkle and friends public space"
url: https://bullwinkle.space

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
    values:
      layout: "default"

collections:
  authors:
    output: true

#lsi: true
permalink: /:categories/:year/:month/:day/:title/
page_excerpts: true
# paginate: 5
# paginate_path: "/blog/page:num/"
collections_dir: collections

sass:
  style: compressed

plugins:  
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-datapage-generator
# - jekyll-manager

livereload: true
