title: Bullwinkle org
remote_theme: ItsMeaga1n/minimal-categorized
subtitle: "Public monitoring page"
description: "[description]"
share: "[share]"
url: https://bullwinkle.ml
permalink: pretty
exclude: ['node_modules']
