title: Bullwinkle org
theme: jekyll-theme-minimal
subtitle: "Public monitoring page"
description: "[description]"
share: "[share]"
url: https://bullwinkle.ml
permalink: pretty
exclude: ['node_modules']
